#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e sb-popupgrade ;;
	2) notify-send "$(/usr/bin/pacman -Qu)" ;;
	3) notify-send "🎁 Upgrade module" "📦: number of upgradable packages
- Left click to upgrade packages
- Middle click to show upgradable packages" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

icon=""
fgcolor="^c#b294bb^"
bgcolor="^b#222222^"
pkgs=$(pacman -Qu | wc -l)

#echo "$bgcolor$fgcolor $icon$pkgs "
echo "$fgcolor$icon$pkgs"
